### ISSUE TITLE
TypeError: Cannot read property 'memo' of undefined

### ISSUE THREAD

**Issue by slifin** [roman01la/proton-native-cljs#1]
<img width="1437" alt="Screenshot 2020-01-20 at 18 29 33" src="https://user-images.githubusercontent.com/198857/72749799-e5922880-3bb2-11ea-812a-ffdc9eefca01.png">

```
node main.js
The above error occurred in the <qi> component:
    in qi

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
/Users/adriansmith/Code/proton-native-cljs/node_modules/react-reconciler/cjs/react-reconciler.development.js:1944
      throw error;
      ^

TypeError: Cannot read property 'memo' of undefined
    at Wh (/Users/adriansmith/Code/proton-native-cljs/out/main.js:342:275)
    at Ph (/Users/adriansmith/Code/proton-native-cljs/out/main.js:344:462)
    at new qi (/Users/adriansmith/Code/proton-native-cljs/out/main.js:357:144)
    at /Users/adriansmith/Code/proton-native-cljs/node_modules/react-proxy/modules/createClassProxy.js:96:24
    at instantiate (/Users/adriansmith/Code/proton-native-cljs/node_modules/react-proxy/modules/createClassProxy.js:104:9)
    at qi (eval at proxyClass (/Users/adriansmith/Code/proton-native-cljs/node_modules/react-proxy/modules/createClassProxy.js:110:22), <anonymous>:4:17)
    at renderWithHooks (/Users/adriansmith/Code/proton-native-cljs/node_modules/react-reconciler/cjs/react-reconciler.development.js:6036:18)
    at mountIndeterminateComponent (/Users/adriansmith/Code/proton-native-cljs/node_modules/react-reconciler/cjs/react-reconciler.development.js:8570:13)
    at beginWork$1 (/Users/adriansmith/Code/proton-native-cljs/node_modules/react-reconciler/cjs/react-reconciler.development.js:9938:16)
    at Object.invokeGuardedCallbackImpl (/Users/adriansmith/Code/proton-native-cljs/node_modules/react-reconciler/cjs/react-reconciler.development.js:11563:10)
```

**Comment by roman01la** [comment]
no idea what's wrong, this is not a project that takes any issues or feature requests, closing it
